# Generated by Django 3.1.7 on 2021-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.SlugField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255)),
                ('audienceNumber', models.IntegerField()),
                ('entryCost', models.FloatField()),
                ('ageRange', models.CharField(choices=[('AA', 'All Ages'), ('18', '18+'), ('21', '21+')], max_length=2)),
            ],
        ),
    ]
