# Generated by Django 3.1.7 on 2021-11-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideathonwebapp', '0002_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
