# Generated by Django 3.1.7 on 2021-11-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideathonwebapp', '0006_auto_20211106_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
